-- MySQL Script generated by MySQL Workbench
-- Tue Jul 12 02:49:05 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema event_management
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `event_management` ;

-- -----------------------------------------------------
-- Schema event_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `event_management` DEFAULT CHARACTER SET utf8 ;
USE `event_management` ;

-- -----------------------------------------------------
-- Table `event_management`.`event_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_management`.`event_category` ;

CREATE TABLE IF NOT EXISTS `event_management`.`event_category` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  `creation_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11111138
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `title_UNIQUE` ON `event_management`.`event_category` (`title` ASC);


-- -----------------------------------------------------
-- Table `event_management`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_management`.`event` ;

CREATE TABLE IF NOT EXISTS `event_management`.`event` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `short_desc` VARCHAR(300) NULL DEFAULT NULL,
  `full_desc` VARCHAR(1500) NULL DEFAULT NULL,
  `location` VARCHAR(200) NULL DEFAULT NULL,
  `lat` FLOAT NULL DEFAULT NULL,
  `lng` FLOAT NULL DEFAULT NULL,
  `file_path` VARCHAR(255) NULL DEFAULT NULL,
  `image_path` VARCHAR(255) NULL DEFAULT NULL,
  `category_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `public_accessed` TINYINT(4) NOT NULL DEFAULT '1',
  `guests_allowed` TINYINT(4) NOT NULL DEFAULT '0',
  `start` DATETIME NULL DEFAULT NULL,
  `end` DATETIME NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `event_management`.`event_category` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 111239
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `event_id_UNIQUE` ON `event_management`.`event` (`id` ASC);

CREATE INDEX `event_category_idx` ON `event_management`.`event` (`category_id` ASC);


-- -----------------------------------------------------
-- Table `event_management`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_management`.`user` ;

CREATE TABLE IF NOT EXISTS `event_management`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(30) NULL DEFAULT NULL,
  `avatar_path` VARCHAR(300) NULL DEFAULT NULL,
  `verified` TINYINT(1) NULL DEFAULT NULL,
  `registration_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 111398
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `email_UNIQUE` ON `event_management`.`user` (`email` ASC);

CREATE UNIQUE INDEX `username_UNIQUE` ON `event_management`.`user` (`username` ASC);


-- -----------------------------------------------------
-- Table `event_management`.`event_invitation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_management`.`event_invitation` ;

CREATE TABLE IF NOT EXISTS `event_management`.`event_invitation` (
  `event_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `user_role` ENUM('Member', 'Organizer') NULL DEFAULT 'Member',
  `user_response` ENUM('Yes', 'No', 'Maybe', 'Undefined') NULL DEFAULT 'Undefined',
  `attendees_count` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  `participated` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`event_id`, `user_id`),
  CONSTRAINT `fk_ event_invitation_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `event_management`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ event_invitation_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `event_management`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `user_id_idx` ON `event_management`.`event_invitation` (`user_id` ASC);

CREATE INDEX `event_id_idx` ON `event_management`.`event_invitation` (`event_id` ASC);


-- -----------------------------------------------------
-- Table `event_management`.`event_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_management`.`event_media` ;

CREATE TABLE IF NOT EXISTS `event_management`.`event_media` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` INT(10) UNSIGNED NOT NULL,
  `path` VARCHAR(300) NOT NULL,
  `type` ENUM('Image', 'Video') NOT NULL,
  `description` VARCHAR(300) NULL DEFAULT NULL,
  `uploader_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `upload_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_media_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `event_management`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_media_uploaded_by`
    FOREIGN KEY (`uploader_id`)
    REFERENCES `event_management`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `event_id_idx` ON `event_management`.`event_media` (`event_id` ASC);

CREATE INDEX `uploaded_by_idx` ON `event_management`.`event_media` (`uploader_id` ASC);


-- -----------------------------------------------------
-- Table `event_management`.`recurrence_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_management`.`recurrence_type` ;

CREATE TABLE IF NOT EXISTS `event_management`.`recurrence_type` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `interval_unit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `title_UNIQUE` ON `event_management`.`recurrence_type` (`title` ASC);


-- -----------------------------------------------------
-- Table `event_management`.`event_recurrence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_management`.`event_recurrence` ;

CREATE TABLE IF NOT EXISTS `event_management`.`event_recurrence` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) UNSIGNED NOT NULL,
  `recurrence_type_id` INT(11) UNSIGNED NOT NULL,
  `repeat_interval` INT(11) UNSIGNED NOT NULL,
  `repeat_on` INT(10) UNSIGNED NULL DEFAULT NULL,
  `repeat_end` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_recurrence_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `event_management`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_recurrence_recurrence_type_id`
    FOREIGN KEY (`recurrence_type_id`)
    REFERENCES `event_management`.`recurrence_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_event_recurrence_event_id_idx` ON `event_management`.`event_recurrence` (`event_id` ASC);

CREATE INDEX `fk_event_recurrence_recurrence_type_idx` ON `event_management`.`event_recurrence` (`recurrence_type_id` ASC);


-- -----------------------------------------------------
-- Table `event_management`.`repeat_on_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_management`.`repeat_on_value` ;

CREATE TABLE IF NOT EXISTS `event_management`.`repeat_on_value` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `recurrence_type_id` INT(11) UNSIGNED NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_repeat_on_value_rec_type_id`
    FOREIGN KEY (`recurrence_type_id`)
    REFERENCES `event_management`.`recurrence_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repeat_on_value_rec_type_id_idx` ON `event_management`.`repeat_on_value` (`recurrence_type_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
